### ISSUE TITLE
unhandled error when running cordova-splash

### ISSUE THREAD

**Issue by cryr** [AlexDisler/cordova-splash#29]
Im getting a error when i run cordova-splash in my root folder:

```
Checking Project & Splash

  V  platforms found: android
  V  splash.png exists
  V  config.xml exists

 Generating splash screen for android

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn identify ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

```

ImageMagick is installed.
nodejs version: 4.4.3

Any help is much appreciated.

**Comment by OleCordsen** [comment]
I'm getting the same error. Is your operating system OSX, too? I'm also using cordova-icon, which works, so ImageMagick should be okay.

**Comment by tdascoli** [comment]
I also getting the same error. OSX

**Comment by rodneicouto** [comment]
A get this error too!

**Comment by Wolf-P** [comment]
Slightly different lines, but same problem (Windows 10)

 Checking Project & Splash

  ✓  platforms found: android
  ✓  splash.png exists
  ✓  config.xml exists

 Generating splash screen for android

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn identify ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by Wolf-P** [comment]
I had the same problem with cordova icon, the solution there made this splash also work for me

> Problem on my side was that imagemagick was not installed correctly. Make sure to check "Install legacy components (convert.exe etc)" and be sure that imagemagick comes before system32 in environmental variables path.

**Comment by karlperemil** [comment]
having the same issue

**Comment by BruceGitHub** [comment]
having the same issue

**Comment by okonuskan** [comment]
I had the same problem with OSX. I downloaded and installer **imagemagick** from a .pkg file, but it turned that I needed to install with **brew install imagemagick**.

Hope it helps!

**Comment by ekntrtmz** [comment]
Having the same problem. Tried to solve this with the suggestions Wolf-P made and reinstalled imagemagick with legacy components. But could not figure out how tocheck/ change environmental variables path.

**Comment by roy46** [comment]
Thanks @Wolf-P. Installing the additional components fixed this issue for me on Windows 10.

**Comment by kgroat** [comment]
The correct solution is as @Wolf-P pointed out, but it might be good to have a meaningful error message when this issue arises.

**Comment by FabianGosebrink** [comment]
Having the same error. Imagemagick is installed and available over commandline. Icon exists which cordova-splash confirms. in the PATH the imagemagick entry comes at first before every other entry. Any recommendations?

**Comment by jesseppku** [comment]
mute




  
  
  


  
    
      
          
            
              
            
            
              jesse cheng
            
          
            
              
                  邮箱：zhenghuijie@gmail.com
              
            
      
    
  


签名由 网易邮箱大师 定制
On 01/02/2018 23:31, Fabian Gosebrink wrote: Having the same error. Imagemagick is installed and available over commandline. Icon exists which cordova-splash confirms. in the PATH the imagemagick entry comes at first before every other entry. Any recommendations?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AlexDisler/cordova-splash","title":"AlexDisler/cordova-splash","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AlexDisler/cordova-splash"}},"updates":{"snippets":[{"icon":"PERSON","message":"@FabianGosebrink in #29: Having the same error. Imagemagick is installed and available over commandline. Icon exists which cordova-splash confirms. in the PATH the imagemagick entry comes at first before every other entry. Any recommendations? "}],"action":{"name":"View Issue","url":"https://github.com/AlexDisler/cordova-splash/issues/29#issuecomment-354792107"}}}

**Comment by guilhermelirio** [comment]
The same error with me. Using Windows 10. How to solve?

```
Checking Project & Splash

  V  platforms found: android
  V  splash.png exists
  V  config.xml exists

 Generating splash screen for android

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn identify ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```
