### ISSUE TITLE
Events.js:160

### ISSUE THREAD

**Issue by andymoyle** [AlexDisler/cordova-splash#40]
Hi there
here's what I get (with just android & android and ios platforms)

events.js:160
throw er; //Unhandled error event

Error: spawn identify ENOENT
at exports._errnoException (util.js:1022:11)
at Provess.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:359:16)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)

Any ideas? - running on Windows, installed today 30th Dec 2016

**Comment by BrunoCartier** [comment]
Hi,

Did you check "legacy tools" when installing ImageMagick?

**Comment by BrunoCartier** [comment]
No response, closing. Feel free to re-open if needed.
