### ISSUE TITLE
0.11.0 fails to run for Android

### ISSUE THREAD

**Issue by zarko-tg** [AlexDisler/cordova-splash#51]
Error: Command failed: cordova-splash --splash=config/splash.png
module.js:540
    throw err;
    ^

Error: Cannot find module '../../platforms/android/cordova/version'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at getAndroidFolder (/Users/zarko/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-splash/index.js:27:16)
    at getPlatforms (/Users/zarko/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-splash/index.js:73:18)
    at atLeastOnePlatformFound (/Users/zarko/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-splash/index.js:243:3)
    at Object.<anonymous> (/Users/zarko/.nvm/versions/node/v8.9.4/lib/node_modules/cordova-splash/index.js:300:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)

**Comment by AlexDisler** [comment]
Should be resolved in the latest version
